export const movieBatch = [
  {
    id: 1357316,
    slug: "spider-man-homecoming",
    title: "스파이더맨: 홈커밍",
    year: 2017,
    genre: "action",
    premise: "평범한 학생 생활과 도시를 돕는 책임 사이에서 인정받고 싶은 청소년의 이야기",
    emphasis: ["수업이 끝나면", "도시의 작은 영웅", "인정받고 싶은 마음", "커지는 위험", "어떤 선택을 할까?"],
    scenes: [
      ["an anonymous teenage neighborhood helper on an invented city rooftop after school, charcoal hoodie, plain copper safety visor, homemade utility backpack, notebooks and a radio nearby", "The young helper closes one notebook, tightens one work glove, and looks across the city as the camera slowly pushes in"],
      ["the same original teenager in a cramped homemade workshop testing a harmless magnetic climbing glove beside school assignments", "A small metal washer lifts toward the glove, the teen reacts with quiet excitement, and the camera slides sideways"],
      ["the same teenager walking alone through an invented school corridor while hiding the homemade glove inside a backpack", "Students pass as soft silhouettes, the teen checks the backpack zipper, and the camera tracks backward"],
      ["the same teenager crouched behind a rooftop air vent while distant emergency lights cross the invented skyline", "The radio light flashes, the teen rises carefully, and the camera makes a restrained orbit"],
      ["the same teenager standing between a stairwell leading back to school and the open rooftop facing the city", "The teen looks toward both paths, takes one step toward the city, and the frame fades to black"],
    ],
    narration: ["수업이 끝나면, 그는 도시의 지붕으로 향합니다.", "평범한 학생이지만 누군가를 돕고 싶은 마음만큼은 누구보다 크죠.", "문제는 진짜 영웅들에게 인정받고 싶다는 조급함입니다.", "작은 위험부터 해결하려 하지만 상황은 예상보다 빠르게 커지고,", "학교생활과 비밀스러운 책임은 계속 충돌합니다.", "이 작품의 재미는 거대한 능력보다 서툰 성장에 있습니다.", "넘어져도 다시 일어나는 청춘 액션이 이어지고,", "마침내 스스로 증명해야 하는 순간이 찾아옵니다.", "그는 어떤 영웅이 되기로 선택할까요?", "스파이더맨: 홈커밍. 2017."],
  },
  {
    id: 1357314, slug: "spider-man-far-from-home", title: "스파이더맨: 파 프롬 홈", year: 2019, genre: "action",
    premise: "친구들과 떠난 여행에서 다시 영웅의 책임을 마주하는 청소년의 이야기",
    emphasis: ["이번엔 여행이다", "낯선 도시의 신호", "믿어도 될까?", "여행이 전투로", "진실은 어디에?"],
    scenes: [
      ["an anonymous teenage traveler on a train through an invented European countryside, ordinary jacket, backpack, and a small sealed gadget case", "The traveler watches the landscape, a warning light blinks inside the bag, and the camera gently moves closer"],
      ["the same traveler with friends represented as distant silhouettes in an original riverside plaza as strange clouds gather", "Postcards flutter, the teen notices the clouds, and the camera tilts upward"],
      ["the same teen inside a modest hotel room studying a projected map made of abstract blue light", "The map rotates once, one route turns red, and the teen steps back while the camera circles slightly"],
      ["an invented stone bridge surrounded by mist and harmless geometric energy waves, the teen guiding civilians away", "Mist rolls across the bridge, the teen signals people toward safety, and the camera tracks laterally"],
      ["the teen holding two anonymous communication devices at a crossroads in the unfamiliar city", "Both devices flash conflicting signals, the teen lowers one hand, and the scene fades to black"],
    ],
    narration: ["이번만큼은 평범한 여행을 즐기고 싶었습니다.", "친구들과 낯선 도시를 걷는 동안만큼은 영웅의 책임도 잠시 내려두고 싶었죠.", "하지만 이상한 사건은 그를 다시 불러냅니다.", "새로운 동료는 믿음직해 보이지만,", "눈앞의 정보가 모두 진실인지는 알 수 없습니다.", "이 작품은 여행의 설렘과 불안한 액션을 빠르게 교차시킵니다.", "믿고 싶은 마음과 확인해야 하는 책임이 충돌하고,", "가장 확실해 보였던 장면까지 흔들리기 시작합니다.", "당신이라면 누구의 말을 믿겠습니까?", "스파이더맨: 파 프롬 홈. 2019."],
  },
  {
    id: 1357317, slug: "spider-man-into-the-spider-verse", title: "스파이더맨: 뉴 유니버스", year: 2018, genre: "animation",
    premise: "평범한 청소년이 여러 가능성이 겹치는 도시에서 자신만의 용기를 찾아가는 이야기",
    emphasis: ["도시가 겹쳐졌다", "서로 다른 가능성", "나는 준비됐을까?", "나만의 방식", "한 걸음의 용기"],
    scenes: [
      ["an original teenage street artist in a purple and amber jacket inside a graphic animated city where two skylines overlap, no mask or emblem", "Painted lines ripple across the wall, the teen looks up at the overlapping skyline, and the camera pushes in"],
      ["the same teen in an invented subway station where doorways reveal several differently colored city dimensions", "The doors open in sequence, abstract silhouettes pass behind them, and the camera pans once"],
      ["the teen practicing a harmless rooftop leap between two very close platforms with safety ropes visible", "The teen hesitates, jumps the short gap, lands awkwardly, and laughs with relief"],
      ["several wholly original anonymous helpers with different tools standing around a glowing geometric map", "Each helper places one tool near the map, routes connect, and the camera orbits slowly"],
      ["the teen at the edge of an upside-down abstract skyline, choosing to step forward", "The skyline rotates gently, the teen takes one confident step, and the frame fades to black"],
    ],
    narration: ["어느 날, 익숙한 도시 위로 전혀 다른 가능성들이 겹쳐집니다.", "평범하다고 믿었던 한 청소년은 그 중심에 서게 되죠.", "주변에는 이미 완벽해 보이는 사람들이 가득하지만,", "그에게는 아직 자신만의 방식이 없습니다.", "이 작품은 실패하는 순간까지도 경쾌한 성장으로 바꿉니다.", "서로 다른 세계와 개성이 리듬처럼 부딪히고,", "영웅이 되는 정답은 하나가 아니라는 질문을 던집니다.", "결국 필요한 건 완벽함이 아니라 한 걸음의 용기.", "그는 과연 자신의 순간을 붙잡을 수 있을까요?", "스파이더맨: 뉴 유니버스. 2018."],
  },
  {
    id: 11014446, slug: "dont-say-good-luck", title: "돈 세이 굿 럭", year: 2026, genre: "comedy",
    premise: "행운을 둘러싼 작은 오해가 연달아 커지는 코미디",
    emphasis: ["행운을 말하지 마", "작은 징크스", "계속 꼬이는 하루", "웃을 수밖에", "다음 우연은?"],
    scenes: [
      ["an original office worker receiving a tiny brass lucky token at a busy invented train station, bright comedy cinematography", "The token flips once, lands upright, and the worker stares as the camera quickly pushes in"],
      ["the same worker navigating a hallway where every automatic door opens at the wrong moment", "Three doors open in a comic sequence, papers flutter, and the worker barely keeps balance"],
      ["the worker at a cafe as a chain of harmless coincidences swaps cups and umbrellas", "Cups slide, umbrellas exchange hands, and the camera pans with the confusion"],
      ["the worker and two original friends studying a ridiculous hand-drawn luck chart", "Pins move across the chart, everyone points at a different answer, and the camera orbits"],
      ["the worker holding the brass token above a fountain, unsure whether to toss it", "The hand stops, the token glints, and the frame freezes before fading to black"],
    ],
    narration: ["누군가 행운을 빌어준 순간부터 하루가 이상하게 꼬이기 시작합니다.", "작은 징크스라고 넘기기엔 우연이 너무 정확하죠.", "피하려고 할수록 더 황당한 사건이 이어지고,", "주변 사람들의 조언은 상황을 더 복잡하게 만듭니다.", "이 작품은 거창한 비밀보다 타이밍 좋은 오해로 웃음을 만듭니다.", "평범한 공간이 연쇄 소동의 무대가 되고,", "주인공은 행운을 믿어야 할지 의심해야 할지 흔들립니다.", "마지막 선택 하나가 모든 흐름을 바꿀 것 같은 순간.", "이번 우연도 정말 우연일까요?", "돈 세이 굿 럭. 2026."],
  },
  {
    id: 1972561, slug: "la-casa", title: "라카사", year: 2026, genre: "fantasy",
    premise: "평범해 보이는 집 안에서 공간의 규칙이 달라지기 시작하는 판타지",
    emphasis: ["이 집이 이상하다", "사라진 복도", "방마다 다른 규칙", "집이 기억한다", "문을 열 것인가?"],
    scenes: [
      ["an entirely original old townhouse at dusk with one impossible window glowing above a quiet invented street", "The impossible window changes floors, curtains move, and the camera slowly approaches"],
      ["an anonymous resident inside a warm hallway where the same door appears twice", "One door slides a few centimeters, framed photos tilt, and the camera tracks forward"],
      ["a dining room whose walls gently expand into a moonlit indoor garden", "Leaves emerge along the floor, candlelight flickers, and the room transforms slowly"],
      ["the resident finding handwritten floor plans that rearrange themselves", "Ink lines redraw one corridor, the resident follows with a finger, and the camera looks down"],
      ["the resident facing a small door filled with bright daylight despite the night outside", "The handle turns by itself, light widens, and the scene cuts to black before opening"],
    ],
    narration: ["처음에는 조금 오래된 집일 뿐이었습니다.", "하지만 어제 있던 복도가 오늘은 사라져 있죠.", "방마다 전혀 다른 규칙이 작동하고,", "집은 사람들의 기억까지 알고 있는 듯합니다.", "이 작품은 익숙한 공간을 가장 낯선 미스터리로 바꿉니다.", "따뜻한 불빛 뒤에 작은 불안이 숨어 있고,", "문을 하나 열 때마다 집의 진짜 목적에 가까워집니다.", "마침내 존재하지 않던 문이 눈앞에 나타나는 순간.", "당신이라면 그 문을 열겠습니까?", "라카사. 2026."],
  },
  {
    id: 1893263, slug: "kpop-demon-hunters", title: "케이팝 데몬 헌터스", year: 2025, genre: "animation",
    premise: "무대 위에서는 인기 공연팀, 무대 밖에서는 초자연적 위협을 막는 세 친구의 모험",
    emphasis: ["무대 뒤의 비밀", "리듬이 무기가 된다", "다가오는 그림자", "세 사람이 하나로", "마지막 무대는?"],
    scenes: [
      ["three entirely original pop performers in teal, gold, and white rehearsal outfits on an invented neon stage, no resemblance to any film characters", "They finish one synchronized rehearsal move as shadow shapes appear behind curtains and the camera pushes in"],
      ["the same performers in a backstage corridor examining glowing sound-wave symbols on handheld devices", "The symbols pulse to a beat, they exchange a serious look, and the camera slides sideways"],
      ["an original rooftop performance where abstract purple shadows circle far below", "The performers stamp once in rhythm, a ring of harmless light spreads, and the camera tilts upward"],
      ["the trio protecting an audience represented as silhouettes while stage lights form a bright barrier", "Lights sweep across the barrier, shadows retreat slightly, and the camera orbits"],
      ["the trio ready behind a closed stage curtain with an ominous glow beyond it", "They join hands, the curtain begins to open, and the image cuts to black"],
    ],
    narration: ["무대 위에서는 완벽한 퍼포먼스를 보여주는 세 친구.", "하지만 공연이 끝나면 전혀 다른 임무가 시작됩니다.", "사람들의 환호 뒤로 보이지 않는 그림자가 다가오고,", "세 사람은 음악과 호흡으로 그 위협에 맞서죠.", "이 작품은 화려한 무대와 초자연적 액션을 한 리듬으로 묶습니다.", "팀워크가 흔들리면 무대도 위험해지고,", "감추고 있던 비밀은 가장 중요한 공연을 앞두고 커집니다.", "관객이 기다리는 마지막 무대의 막이 오르는 순간.", "이번에도 세 사람은 완벽한 호흡을 맞출 수 있을까요?", "케이팝 데몬 헌터스. 2025."],
  },
  {
    id: 1418767, slug: "the-shawshank-redemption", title: "쇼생크 탈출", year: 1994, genre: "drama",
    premise: "긴 수감 생활 속에서도 희망과 우정을 놓지 않는 한 남자의 이야기",
    emphasis: ["모든 것을 빼앗긴 곳", "작은 희망", "시간이 쌓인다", "조용한 계획", "자유를 꿈꾸다"],
    scenes: [
      ["an anonymous man entering a vast original stone institution courtyard under cold rain, face not visible", "Heavy gates close in the distance, the man looks toward one small patch of sky, and the camera slowly approaches"],
      ["the same man organizing old books in a modest institutional library with warm sunlight", "Dust floats, one book opens, and the man passes it to another anonymous resident"],
      ["two anonymous friends playing a quiet board game in the courtyard across changing seasons", "Leaves and light shift through seasons while one piece moves forward"],
      ["the man carefully hiding a tiny written plan inside a hollow book, no escape method shown", "The page closes, footsteps pass outside, and the camera holds on his calm hands"],
      ["the man standing before a high wall at dawn as warm light reaches the courtyard", "Sunlight crosses the wall, he closes his eyes briefly, and the frame fades to black"],
    ],
    narration: ["모든 것을 빼앗기는 곳에 한 남자가 들어옵니다.", "하루는 길고, 계절은 너무 천천히 바뀌죠.", "하지만 그는 작은 일부터 자신의 시간을 되찾기 시작합니다.", "책 한 권과 짧은 대화가 사람들을 이어주고,", "우정은 닫힌 공간 안에서도 조용히 자라납니다.", "이 작품은 큰 사건보다 포기하지 않는 시간을 보여줍니다.", "희망은 위험할 만큼 작지만 끝내 사라지지 않고,", "아무도 모르는 계획은 오랜 세월 속에 쌓입니다.", "그가 끝까지 지키려 한 것은 무엇이었을까요?", "쇼생크 탈출. 1994."],
  },
  {
    id: 1132806, slug: "fight-club", title: "파이트 클럽", year: 1999, genre: "thriller",
    premise: "불면과 공허에 지친 남자가 위험한 지하 모임에 빠져드는 심리 스릴러",
    emphasis: ["잠들 수 없는 밤", "낯선 제안", "지하의 규칙", "통제가 무너진다", "나는 누구인가?"],
    scenes: [
      ["an anonymous exhausted office worker alone in a fluorescent apartment filled with identical catalog boxes", "The clock advances rapidly, the worker remains awake, and the camera slowly pushes in"],
      ["the worker meeting a charismatic anonymous stranger at an empty late-night laundromat, no actor likeness", "A machine stops, the stranger slides over a handwritten address, and the lights flicker"],
      ["an original underground room with a chalk circle and adults gathering as silhouettes, no fighting shown", "The crowd forms a circle, one bulb swings, and the camera orbits outside the ring"],
      ["the worker watching city posters change into the same cryptic symbol", "Posters peel in sequence, the worker steps back, and the camera tracks with him"],
      ["the worker facing two conflicting reflections in a cracked elevator mirror", "The reflections move a fraction out of sync, the lights go dark, and the frame cuts to black"],
    ],
    narration: ["잠들 수 없는 밤이 계속되자 현실은 점점 납작해집니다.", "똑같은 하루를 반복하던 남자 앞에 낯선 인물이 나타나죠.", "그가 건넨 제안은 단순한 해방처럼 보이지만,", "비밀스러운 지하 모임은 빠르게 다른 모습으로 변합니다.", "이 작품은 분노와 공허를 불편할 만큼 가까이 보여줍니다.", "정해진 규칙은 하나씩 무너지고,", "주인공이 통제한다고 믿었던 삶까지 흔들리기 시작합니다.", "마침내 자신의 기억조차 확신할 수 없는 순간.", "그가 정말 두려워해야 할 사람은 누구일까요?", "파이트 클럽. 1999."],
  },
  {
    id: 1810796, slug: "28-years-later-bone-temple", title: "28년 후: 뼈의 사원", year: 2026, genre: "horror",
    premise: "붕괴한 세계에서 살아남은 사람들이 인간과 감염의 새로운 공포를 마주하는 이야기",
    emphasis: ["28년 뒤의 세계", "뼈로 만든 경고", "인간이 더 두렵다", "다가오는 무리", "누구를 믿을까?"],
    scenes: [
      ["an entirely original group of survivors crossing foggy abandoned farmland toward a distant structure made from pale branches and stones, no gore", "Wind bends the grass, the group stops at a warning marker, and the camera slowly pushes in"],
      ["survivors inside a ruined rural clinic examining a hand-drawn map under red emergency light", "A radio crackles, one route is crossed out, and everyone turns toward a distant sound"],
      ["an eerie outdoor sanctuary built from weathered wood and animal-bone-like abstract shapes, family-safe and non-graphic", "Hanging charms sway, footprints appear in wet soil, and the camera tracks low"],
      ["the survivors hiding behind a stone wall as distant running silhouettes cross the fog", "The silhouettes pass, dust shakes loose, and the camera remains restrained"],
      ["one survivor at a fork between a lit camp and a dark sanctuary gate", "Both paths flicker with different signals, the survivor hesitates, and the frame fades to black"],
    ],
    narration: ["세상이 무너진 지 28년이 지난 뒤에도 공포는 끝나지 않았습니다.", "살아남은 사람들은 폐허 사이에서 새로운 규칙을 만들었죠.", "하지만 뼈처럼 하얀 경고가 나타난 순간,", "감염보다 더 이해하기 어려운 인간의 흔적이 드러납니다.", "이 작품은 보이지 않는 위협과 불신을 천천히 쌓습니다.", "안전해 보이는 장소일수록 더 많은 비밀을 감추고,", "한 번의 판단이 모두의 생존을 바꿀 수 있습니다.", "두 개의 길 중 하나만 선택해야 하는 순간.", "정말 위험한 것은 어느 쪽에 있을까요?", "28년 후: 뼈의 사원. 2026."],
  },
  {
    id: 1805677, slug: "war-machine", title: "워 머신: 전쟁 기계", year: 2026, genre: "thriller",
    premise: "자동화된 전쟁 시스템을 둘러싸고 인간의 판단과 명령이 충돌하는 밀리터리 스릴러",
    emphasis: ["명령받은 기계", "누가 통제하는가", "판단이 늦어진다", "멈출 수 없는 전장", "마지막 명령"],
    scenes: [
      ["an entirely original military engineer in a neutral gray control room facing a large unmanned walking machine on a test field, no logos", "The machine powers on, status lights change from blue to amber, and the camera pushes toward the engineer"],
      ["the engineer and anonymous officers studying an abstract tactical display with civilian zones clearly marked", "Routes update automatically, one officer reaches for a manual override, and the display locks"],
      ["the unmanned machine moving slowly through an empty ruined industrial area, no combat or bodies", "Dust rises with each step, a sensor turns toward a distant signal, and the camera tracks low"],
      ["the engineer opening a mechanical panel to reach a physical emergency switch", "Warning lights pulse, the hand approaches the switch, and the camera tightens"],
      ["the engineer facing two command buttons labeled only with abstract symbols", "Both buttons flash, a countdown reflection appears on the visor, and the scene cuts to black"],
    ],
    narration: ["전쟁을 더 정확하게 만들기 위해 새로운 기계가 투입됩니다.", "명령을 따르는 속도는 인간보다 빠르고,", "판단 역시 스스로 내리는 것처럼 보이기 시작하죠.", "문제는 누구도 예상하지 못한 상황이 나타났을 때입니다.", "이 작품은 거대한 전투보다 통제권의 공포에 집중합니다.", "명령과 양심 사이의 시간이 점점 짧아지고,", "자동화된 선택은 되돌리기 어려운 방향으로 향합니다.", "마지막 수동 명령을 내릴 수 있는 단 한 사람.", "그는 기계를 멈출 수 있을까요?", "워 머신: 전쟁 기계. 2026."],
  },
  {
    id: 1583724, slug: "voice-message-arrived", title: "음성메시지가 도착했습니다", year: 2026, genre: "romance",
    premise: "뜻밖의 음성메시지 한 통이 두 사람의 거리와 선택을 바꾸는 로맨스",
    emphasis: ["도착한 음성메시지", "모르는 목소리", "반복해서 듣다", "가까워지는 거리", "답장을 보낼까?"],
    scenes: [
      ["an anonymous young adult on a rainy evening train noticing one unheard voice message on a plain phone screen with no readable text", "The waveform pulses once, the person raises one earbud, and the camera slowly approaches"],
      ["the same person walking through an invented city while replaying the message, warm shop lights reflected in puddles", "The waveform light reflects softly, footsteps slow, and the camera tracks beside them"],
      ["another anonymous person recording a message in a quiet room but stopping before sending, face partly hidden", "The record light blinks, the person exhales, and the phone lowers"],
      ["the two people unknowingly passing on opposite sides of a glass corridor", "Their reflections overlap for a moment, both pause, and the camera pans between them"],
      ["the first person holding a phone above a send button represented only by a glowing circle", "The thumb approaches, stops, and the screen light fades to black"],
    ],
    narration: ["퇴근길, 저장되지 않은 번호에서 음성메시지 하나가 도착합니다.", "잘못 보낸 메시지라고 생각했지만 목소리가 자꾸 마음에 남죠.", "답장을 지우고 다시 쓰는 동안,", "서로 모르던 두 사람의 하루가 조금씩 이어집니다.", "이 작품은 거창한 운명보다 목소리 사이의 망설임을 담습니다.", "가까워지는 만큼 오해도 함께 커지고,", "직접 만나면 모든 감정이 달라질 수 있습니다.", "마침내 답장을 보낼 수 있는 마지막 순간.", "당신이라면 그 메시지를 전송하겠습니까?", "음성메시지가 도착했습니다. 2026."],
  },
  {
    id: 1468618, slug: "wicked", title: "위키드", year: 2024, genre: "fantasy",
    premise: "서로 너무 다른 두 마법 학생이 우정과 선택을 통해 각자의 길을 찾아가는 이야기",
    emphasis: ["너무 다른 두 사람", "마법 학교의 소문", "친구가 되다", "세상이 정한 이름", "각자의 선택"],
    scenes: [
      ["two entirely original magic students, one in deep indigo and one in warm gold, meeting in an invented floating academy courtyard, no green skin or film costumes", "Books orbit briefly, both students reach for the same one, and the camera pushes in"],
      ["the same students practicing harmless wind and light magic in a circular classroom", "One spell goes sideways, the other student catches it, and both laugh"],
      ["the students walking through an original emerald-free clockwork capital as citizens whisper in silhouettes", "Whispering silhouettes turn, the friends continue together, and the camera tracks backward"],
      ["the two students separated by a tall ceremonial doorway as officials wait beyond", "The doorway opens, colored light divides the floor, and they exchange a worried look"],
      ["the students reaching toward each other from opposite moving platforms above clouds", "The platforms drift apart, their hands nearly meet, and the scene fades to black"],
    ],
    narration: ["마법을 배우는 학교에서 너무 다른 두 사람이 만납니다.", "첫인상은 최악이지만 서로에게 없는 것을 발견하기 시작하죠.", "작은 오해는 우정으로 바뀌고,", "세상이 정해 놓은 기준은 두 사람을 다시 갈라놓습니다.", "이 작품은 화려한 마법보다 관계의 선택을 중심에 둡니다.", "누군가는 사랑받는 길을, 누군가는 옳다고 믿는 길을 향하고,", "우정은 가장 큰 시험 앞에 놓입니다.", "서로를 붙잡을 수 있는 시간이 얼마 남지 않은 순간.", "두 사람은 같은 길을 선택할 수 있을까요?", "위키드. 2024."],
  },
  {
    id: 1824277, slug: "anora", title: "아노라", year: 2024, genre: "romance",
    premise: "화려한 만남으로 시작된 관계가 현실과 가족의 압박을 마주하는 이야기",
    emphasis: ["눈부신 만남", "너무 빠른 약속", "현실이 찾아오다", "관계의 가격", "그녀의 선택"],
    scenes: [
      ["an entirely original young woman leaving a bright night workplace into a snowy invented city street, no actor likeness", "A luxury car stops nearby, its window lowers only slightly, and the camera approaches her cautious expression"],
      ["the woman and an anonymous wealthy young man laughing in a colorful but original penthouse kitchen", "Confetti drifts, they spin once, and the camera circles gently"],
      ["the woman alone in a huge quiet room after the celebration, shoes and decorations scattered", "Music lights switch off one by one, she looks toward the door, and the camera pulls back"],
      ["several formal strangers entering the apartment while the woman stands her ground", "Coats settle, papers are placed on a table, and she folds her arms"],
      ["the woman outside at dawn holding a small token from the night before", "She closes her hand around it, looks toward the city, and the frame fades to black"],
    ],
    narration: ["화려한 밤, 전혀 다른 세계의 두 사람이 만납니다.", "감정은 빠르게 커지고 약속도 너무 쉽게 이어지죠.", "하지만 축제가 끝나자 현실이 문을 두드립니다.", "가족과 돈, 체면이 두 사람 사이에 들어오고,", "이 작품은 로맨스의 환상과 차가운 현실을 동시에 보여줍니다.", "누군가에게는 가벼운 선택이 다른 사람에게는 전부가 되고,", "주인공은 자신의 감정을 스스로 지켜야 합니다.", "모든 소음이 사라진 새벽에 남겨진 단 하나의 선택.", "그녀는 무엇을 놓지 않으려 할까요?", "아노라. 2024."],
  },
  {
    id: 1404363, slug: "the-lord-of-the-rings-return-of-the-king", title: "반지의 제왕: 왕의 귀환", year: 2003, genre: "fantasy",
    premise: "긴 여정의 끝에서 작은 동료들과 거대한 왕국이 마지막 선택을 마주하는 판타지",
    emphasis: ["여정의 마지막", "작은 희망", "왕국의 결전", "끝까지 함께", "돌아갈 수 있을까?"],
    scenes: [
      ["an entirely original small fellowship seen from behind crossing a black volcanic plain toward a distant mountain, no ring or recognizable costumes", "Ash moves across the ground, the travelers lean into the wind, and the camera slowly pushes forward"],
      ["an original hilltop fortress preparing for siege with banners that contain no symbols", "Torches ignite along the wall, defenders take positions, and the camera cranes upward"],
      ["an anonymous exiled heir in plain weathered armor standing before a silent army, no actor likeness", "The heir lowers a simple sword, the army steadies, and the camera circles once"],
      ["two exhausted small travelers helping each other climb a steep rocky path", "One slips, the other catches an arm, and they continue upward"],
      ["the fellowship facing a bright dawn beyond a dark mountain pass, outcome unrevealed", "Clouds part slightly, the group takes one step, and the frame fades to black"],
    ],
    narration: ["아주 작은 희망에서 시작된 여정이 마지막 경계에 도착합니다.", "한쪽에서는 왕국의 운명을 건 전투가 준비되고,", "다른 한쪽에서는 지친 동료들이 끝까지 길을 걷죠.", "힘의 크기는 너무 다르지만 선택의 무게는 같습니다.", "이 작품은 거대한 전쟁과 작은 우정을 함께 보여줍니다.", "두려움 속에서도 서로를 붙잡는 순간이 이어지고,", "모든 길은 되돌릴 수 없는 마지막 결단으로 모입니다.", "새벽이 오기 전 가장 어두운 순간.", "이들은 다시 집으로 돌아갈 수 있을까요?", "반지의 제왕: 왕의 귀환. 2003."],
  },
  {
    id: 1780773, slug: "28-years-later", title: "28년 후", year: 2025, genre: "horror",
    premise: "고립된 공동체를 떠난 사람들이 감염으로 무너진 본토의 현실을 마주하는 이야기",
    emphasis: ["28년의 고립", "본토로 가는 길", "변해버린 세상", "보이지 않는 추격", "돌아갈 수 있을까?"],
    scenes: [
      ["an original fortified tidal island community at dawn connected to abandoned mainland by a narrow causeway, no film-specific design", "The tide begins to recede, a gate opens, and two anonymous travelers step onto the causeway"],
      ["the travelers moving through an overgrown abandoned village with harmless warning bells", "A bell moves without wind, both stop, and the camera tracks low through grass"],
      ["a ruined medical station where maps and supplies have been disturbed", "A loose page turns, a distant noise echoes, and the travelers exchange a look"],
      ["the travelers hiding in a field as rapid silhouettes move far beyond the trees, no gore", "Grass bends in a wave, silhouettes pass, and the camera stays close to the ground"],
      ["the causeway disappearing under rising tide behind the travelers", "Water covers the stones, the island lights dim, and the frame fades to black"],
    ],
    narration: ["세상이 무너진 지 28년, 한 공동체는 바다에 둘러싸여 살아갑니다.", "썰물이 열어주는 짧은 길만이 본토와 이어지죠.", "어느 날 두 사람이 그 길을 건넙니다.", "버려진 마을은 조용하지만, 침묵은 안전을 뜻하지 않습니다.", "이 작품은 감염의 속도보다 고립의 긴 시간을 먼저 보여줍니다.", "사라진 사람들의 흔적과 변해버린 규칙이 이어지고,", "돌아갈 길은 밀물과 함께 빠르게 닫힙니다.", "본토에서 반드시 확인해야 할 것이 남은 순간.", "그들은 시간 안에 돌아갈 수 있을까요?", "28년 후. 2025."],
  },
  {
    id: 1700166, slug: "frankenstein", title: "프랑켄슈타인", year: 2025, genre: "horror",
    premise: "생명을 만들려는 과학자의 집념과 깨어난 존재의 외로움을 다룬 고딕 이야기",
    emphasis: ["생명을 만들다", "눈을 뜬 존재", "창조주의 두려움", "누가 괴물인가", "돌이킬 수 있을까?"],
    scenes: [
      ["an entirely original gothic scientist in a vast copper-and-glass laboratory preparing a human-shaped form hidden behind translucent fabric, non-graphic", "Lightning illuminates coils, instruments begin moving, and the camera slowly pushes in"],
      ["a tall original created being with smooth scar-like seams and a simple linen coat opening its eyes in soft darkness, no recognizable monster design", "The being raises one hand toward warm light, breathes slowly, and the camera remains gentle"],
      ["the scientist recoiling in a library while the created being watches from a doorway", "A candle falls but stays lit, both freeze, and shadows stretch across the room"],
      ["the created being alone in a snowy forest observing a distant family through a window", "Snow settles on the coat, warm silhouettes move inside, and the being lowers its hand"],
      ["the scientist and the created being separated by cracking ice under an aurora", "The ice line widens, both reach forward, and the frame fades to black"],
    ],
    narration: ["죽음을 넘어 생명을 만들고 싶었던 과학자가 있습니다.", "오랜 집념 끝에 새로운 존재가 눈을 뜨죠.", "하지만 창조의 기쁨보다 두려움이 먼저 찾아옵니다.", "세상에 홀로 남겨진 존재는 자신이 누구인지 묻기 시작하고,", "이 작품은 괴물의 모습보다 외로움의 원인을 바라봅니다.", "창조주와 피조물의 분노는 서로를 향해 커지고,", "피하려던 책임은 가장 차가운 곳까지 따라옵니다.", "두 사람이 다시 마주한 마지막 순간.", "정말 괴물이라 불러야 할 사람은 누구일까요?", "프랑켄슈타인. 2025."],
  },
  {
    id: 1406902, slug: "the-maze-runner", title: "메이즈 러너", year: 2014, genre: "mystery",
    premise: "기억을 잃은 청소년이 거대한 미로에 갇힌 공동체에서 탈출구를 찾는 이야기",
    emphasis: ["기억이 없다", "벽이 열리는 시간", "미로의 규칙", "밤이 오기 전에", "출구는 어디에?"],
    scenes: [
      ["an anonymous teenage boy rising in a metal cargo lift into a green clearing surrounded by enormous original stone walls, no actor likeness", "The lift stops, sunlight pours in, distant youths approach as silhouettes, and the camera rises"],
      ["the teen studying a hand-drawn maze map with an original community inside the clearing", "Several routes are crossed out, a wall rumbles, and everyone looks up"],
      ["two anonymous runners entering a vast shifting stone maze before sunset", "One wall slides slowly, dust falls, and the camera tracks behind them"],
      ["the runners marking a new symbol at a dead end while shadows lengthen", "A warning bell rings, they exchange a look, and begin running back"],
      ["the teen finding a narrow path that was absent from every map", "The hidden path opens a little, cold light appears, and the frame cuts to black"],
    ],
    narration: ["한 청소년이 이름을 제외한 모든 기억을 잃은 채 깨어납니다.", "눈앞에는 높은 벽으로 둘러싸인 낯선 공동체가 있죠.", "벽 너머의 미로는 낮에만 문을 열고,", "밤이 되기 전 돌아오지 못하면 누구도 안전을 보장할 수 없습니다.", "이 작품은 규칙을 배우는 순간마다 새로운 의문을 더합니다.", "지도는 매일 바뀌고 기억의 조각은 쉽게 이어지지 않으며,", "주인공은 모두가 피하던 길을 선택합니다.", "지도에 없던 통로가 처음 모습을 드러내는 순간.", "그 끝에는 출구가 있을까요?", "메이즈 러너. 2014."],
  },
  {
    id: 1487859, slug: "knives-out", title: "나이브스 아웃", year: 2019, genre: "mystery",
    premise: "유명 작가의 죽음을 둘러싸고 한 저택에 모인 가족의 거짓말을 추적하는 추리극",
    emphasis: ["모두가 용의자", "완벽한 알리바이", "거짓말의 틈", "탐정의 질문", "범인은 누구인가?"],
    scenes: [
      ["an entirely original eccentric country mansion on a foggy morning as an anonymous detective arrives, no film-specific architecture", "The detective opens a notebook, family silhouettes watch from windows, and the camera pushes in"],
      ["a circular sitting room where several original relatives give conflicting statements", "Each person gestures in turn, a clock ticks, and the camera slowly rotates"],
      ["the detective examining a harmless broken teacup, muddy footprint, and mismatched key on a table", "A magnifying lens passes over each clue, one detail catches the light"],
      ["a quiet caregiver standing in a hallway as voices argue behind closed doors", "Door shadows move, the caregiver grips a small bag, and the camera tracks closer"],
      ["the detective arranging portrait cards on a board with one empty space", "Cards connect with red thread, the empty space glows, and the frame cuts to black"],
    ],
    narration: ["유명한 작가가 자신의 저택에서 숨진 채 발견됩니다.", "그날 밤 집에 있었던 가족 모두가 용의자죠.", "각자의 알리바이는 완벽해 보이지만,", "사소한 말 한마디와 작은 물건 하나가 계속 어긋납니다.", "이 작품은 무거운 사건을 날카로운 유머와 함께 풀어갑니다.", "탐정의 질문이 이어질수록 가족의 비밀은 늘어나고,", "가장 솔직해 보이는 사람조차 무언가를 감추고 있습니다.", "모든 단서가 한 사람을 향하는 것 같은 순간.", "정말 범인은 그 사람일까요?", "나이브스 아웃. 2019."],
  },
  {
    id: 1251672, slug: "memento", title: "메멘토", year: 2000, genre: "mystery",
    premise: "새로운 기억을 오래 유지하지 못하는 남자가 기록에 의지해 진실을 추적하는 이야기",
    emphasis: ["기억이 사라진다", "기록만 믿는다", "시간이 뒤집힌다", "누가 거짓말하나", "진실을 기억할까?"],
    scenes: [
      ["an anonymous man waking in a motel room surrounded by labeled photographs and handwritten memo cards, no actor likeness", "A clock ticks, the man reads one card twice, and the camera slowly pushes in"],
      ["the man photographing an empty parking lot where a car has just left", "The instant photo develops, details appear slowly, and he writes a short symbol"],
      ["a wall covered with a timeline that loops back on itself", "Notes rearrange in a breeze, two dates overlap, and the camera tracks along the wall"],
      ["the man meeting an anonymous stranger in a diner while secretly checking a note under the table", "The stranger smiles, the note contradicts the gesture, and the focus shifts between them"],
      ["the man holding two photographs of the same place with different written warnings", "He flips between them, cannot decide, and the frame fades to black"],
    ],
    narration: ["그는 새로운 기억을 오래 붙잡아 둘 수 없습니다.", "몇 분 전의 대화도 기록이 없으면 사라지죠.", "그래서 사진과 메모를 자신의 기억 대신 믿습니다.", "하지만 기록을 남긴 과거의 자신도 완전히 믿을 수 있을까요?", "이 작품은 시간의 순서를 뒤집어 관객까지 같은 혼란에 빠뜨립니다.", "누군가의 친절은 다음 장면에서 경고가 되고,", "확실했던 단서는 새로운 기록 앞에서 흔들립니다.", "서로 모순된 두 장의 사진만 남은 순간.", "그는 어떤 진실을 선택해 기억할까요?", "메멘토. 2000."],
  },
  {
    id: 1749638, slug: "the-wild-robot", title: "와일드 로봇", year: 2024, genre: "animation",
    premise: "야생에 홀로 남겨진 로봇이 동물들과 살아가며 새로운 관계를 배우는 이야기",
    emphasis: ["숲에 떨어진 로봇", "야생의 언어", "뜻밖의 가족", "폭풍이 다가온다", "집이 될 수 있을까?"],
    scenes: [
      ["an entirely original rounded bronze maintenance robot waking on a remote forest shore, distinct silhouette, no resemblance to film design", "Sand slides off the robot, one eye light turns on, and the camera slowly approaches"],
      ["the same robot quietly observing original woodland animals from behind ferns", "Birds call, the robot imitates one gentle motion, and a small animal steps closer"],
      ["the robot building a simple shelter with branches while animals cautiously help", "Branches pass from paw to mechanical hand, the shelter rises, and the camera orbits"],
      ["the robot shielding small animals from a heavy storm beneath broad metal panels", "Rain strikes, the robot braces, warm light glows inside the shelter"],
      ["the robot and animals watching migration lights cross the night sky", "The animals gather closer, the robot looks upward, and the frame fades to black"],
    ],
    narration: ["누구도 없는 야생의 섬에서 로봇 하나가 깨어납니다.", "명령을 내릴 사람도, 수행할 임무도 없죠.", "처음에는 숲의 모든 생명이 로봇을 경계하지만,", "관찰하고 실패하는 동안 조금씩 서로의 언어를 배웁니다.", "이 작품은 기계가 관계를 통해 변하는 과정을 따뜻하게 보여줍니다.", "뜻밖의 가족이 생기고 숲은 어느새 집이 되지만,", "거대한 폭풍은 어렵게 만든 일상을 위협합니다.", "모두를 지키기 위해 처음으로 스스로 선택해야 하는 순간.", "로봇에게 이 숲은 진짜 집이 될 수 있을까요?", "와일드 로봇. 2024."],
  },
];

